name: build-deploy

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [ wordpress ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      GATSBY_ACTIVE_ENV: production
      GATSBY_SITE_URL: 'https://www.bestondesk.com'
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
      GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
      GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
      GATSBY_WP_SOURCE_URL: ${{ secrets.GATSBY_WP_SOURCE_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Set Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Gatsby Cache Folder
        uses: actions/cache@v2
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby-v1
          restore-keys: |
            ${{ runner.os }}-cache-gatsby-v1

      - name: Cache Gatsby Public Folder
        uses: actions/cache@v2
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby-v1
          restore-keys: |
            ${{ runner.os }}-public-gatsby-v1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Gatsby
        run: yarn build

      - name: Deploy
        run: yarn deploy

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
